DROP SCHEMA INVENTORY_MASTER;



CREATE SCHEMA INVENTORY_MASTER;

USE INVENTORY_MASTER;

DROP TABLE IF EXISTS PRODUCT_CATEGORY_INFO;

CREATE TABLE PRODUCT_CATEGORY_INFO(
	PRODUCT_CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_CATEGORY_NAME VARCHAR(100) NOT NULL,
	PRODUCT_CATEGORY_DESC VARCHAR(500) NOT NULL,
	REC_CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REC_CREATED_BY VARCHAR(100) NOT NULL,
	REC_UPDATED_DATE TIMESTAMP,
	REC_UPDATED_BY VARCHAR(100),
	REC_ACTIVE_FLAG INT NOT NULL DEFAULT 1,
	PRIMARY KEY(PRODUCT_CATEGORY_ID)
);

DROP TABLE IF EXISTS PRODUCT_INFO;

CREATE TABLE PRODUCT_INFO (
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_LABEL VARCHAR(100) NOT NULL,
	SUPPLIER_ID INT NOT NULL,
	COST_PRICE DOUBLE NOT NULL,
	SELLING_PRICE DOUBLE NOT NULL,
	PRODUCT_CATEGORY_ID INT NOT NULL,
	PRODUCT_NOTES VARCHAR(2000) NOT NULL,
	REC_CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REC_CREATED_BY VARCHAR(100) NOT NULL,
	REC_UPDATED_DATE TIMESTAMP,
	REC_UPDATED_BY VARCHAR(100),
	REC_ACTIVE_FLAG INT NOT NULL DEFAULT 1,
	PRIMARY KEY(PRODUCT_ID)
);

DROP TABLE IF EXISTS PURCHASE_ORDER_INFO;

CREATE TABLE PURCHASE_ORDER_INFO(
	PURCHASE_ORDER_ID INT NOT NULL AUTO_INCREMENT,
	PURCHASE_ORDER_DATE DATE NOT NULL,
	PRODUCT_ID INT NOT NULL,
	PURCHASE_QUANTITY INT NOT NULL,
	REC_CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REC_CREATED_BY VARCHAR(100) NOT NULL,
	REC_UPDATED_DATE TIMESTAMP,
	REC_UPDATED_BY VARCHAR(100),
	REC_ACTIVE_FLAG INT NOT NULL DEFAULT 1,
	PRIMARY KEY (PURCHASE_ORDER_ID)
);

DROP TABLE IF EXISTS SUPPLIER_INFO;

CREATE TABLE SUPPLIER_INFO (
	SUPPLIER_ID INT NOT NULL AUTO_INCREMENT,
	SUPPLIER_NAME VARCHAR(100) NOT NULL,
	SUPPLIER_ADDRESS VARCHAR(200) NOT NULL,
	SUPPLIER_CONTACT VARCHAR(100),
	REC_CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REC_CREATED_BY VARCHAR(100) NOT NULL,
	REC_UPDATED_DATE TIMESTAMP,
	REC_UPDATED_BY VARCHAR(100),
	REC_ACTIVE_FLAG INT NOT NULL DEFAULT 1,
	PRIMARY KEY (SUPPLIER_ID)
);

DROP TABLE IF EXISTS ORDER_INFO;

CREATE TABLE ORDER_INFO(
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	ORDER_NUMBER INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	DELIVERY_ADDRESS VARCHAR(200) NOT NULL,
	ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ORDER_STATUS_CODE VARCHAR(10) NOT NULL DEFAULT "O",
	PRODUCT_ID INT NOT NULL,
	PRODUCT_QUANTITY INT NOT NULL DEFAULT 1,
	REC_CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REC_CREATED_BY VARCHAR(100) NOT NULL,
	REC_UPDATED_DATE TIMESTAMP,
	REC_UPDATED_BY VARCHAR(100),
	REC_ACTIVE_FLAG INT NOT NULL DEFAULT 1,
	PRIMARY KEY (ORDER_ID)
);

